version: "3"
services:
  app_1:
    container_name: app_1
    build:
      context: .
      dockerfile: Dockerfile_app_1
    depends_on:
      - mysql
      - redis
  app_2:
    container_name: app_2
    build:
      context: .
      dockerfile: Dockerfile_app_2
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    image: docker.io/mysql:8.0
    environment:
      - MYSQL_DATABASE="vps-poc"
      - MYSQL_ROOT_PASSWORD="vpspoc"
      - MYSQL_PASSWORD="1234"
      - MYSQL_USER="vps-poc"
      - SERVICE_NAME="mysql"
    volumes:
      - "mysql-data-volume:/var/lib/mysql"
  redis:
    container_name: redis
    image: docker.io/redis:latest
    volumes:
      - "redis-data-volume:/data"
  load_balancer:
    container_name: load_balancer
    image: docker.io/nginx:stable
    ports:
      - "8080:80"
    volumes:
      - "./load-balancer/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - app_1
      - app_2
volumes:
  mysql-data-volume:
  redis-data-volume:
